_target_: base_model.AsrBaseModule
model:
  _target_: modules.SpeechRecognition.SpeechRecognitionModel
  n_cnn_layers: 3
  n_rnn_layers: 5
  rnn_dim: 512
  n_class: 29
  n_feats: 128
  stride: 2
  dropout: 0.1

optimizer:
  _target_: torch.optim.AdamW
  _partial_: True
  lr: 0.0005

criterion:
  _target_: torch.nn.CTCLoss
  blank: 28
